### ISSUE TITLE
mounting aufs on /root failed: No such device

### ISSUE THREAD

**Issue by AlpNek** [NitruxSA/nitrux-violaceous#1]
Hi,
While starting up Nitrux 7.15 from the USB stick, I stops booting with the above error. I've tried all 3 menu options from Grub (Live, Safe Graphics and Debug) and all of them stop at the above error and (initramfs) prompt.

Thanks,
Ken

**Comment by UriHerrera** [comment]
Hi!,

Yes there's a problem with the new kernel and a new ISO has been created it will be uploaded as soon as possible.

-Uri.

**Comment by darkadan** [comment]
Hi,

In the company we are interested in testing the Nitrux OS distro, not been possible for this bug, only to have test in virtualbox and is not such a real experience.

Any solution to this problem?

Thanks, 
Mario

**Comment by UriHerrera** [comment]
@darkadan The current ISO in our site doesn't present this issue.

**Comment by UriHerrera** [comment]
ISO with SHA1 checksum: 2ece713d65cde2c6bf2df10364c0eb15845f38ca is free of this bug.

**Comment by darkadan** [comment]
Hi,

Exactly desktop version 7.15 was the one to downloaded and this bug ...

Thanks,

El dom., 9 de ago. de 2015 1:47 AM, Uri Herrera <notifications@github.com>
escribió:

> ISO with SHA1 checksum: 2ece713d65cde2c6bf2df10364c0eb15845f38ca is free
> of this bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NitruxSA/nitrux-violaceous/issues/1#issuecomment-129128850>
> .
>
-- 

---
Mario Pardo
Networking Administrator
Stack+

Enviado desde Google Nexus 5

**Comment by UriHerrera** [comment]
I'll be building a new image for the OS, I can't give an ETA of when it'll be ready but make sure that the ISO you have matches that checksum.
